# This is a basic workflow to help you get started with Actions

name: '1.19'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 17

      - name: Compile 1.19 spigot version
        uses: ./
        with:
          versions: 1.19
  # Run the original BuildTools in GitHub Actions to easily compare the build times etc.
  original-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          # This version should probably match the ones from the 'run'-job
          java-version: 17
          distribution: temurin

      - name: Run original Spigot-BuildTools (latest)
        # These versions should match the ones from the 'run'-job
        # Using '--compile Spigot' as this action does the same by default
        run: |
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          java -jar BuildTools.jar --rev latest --compile Spigot
