# This workflow will perform a compilation test on 
# each push to the branch master to check its correct 
# compilation and will deliver an artifact to check 
# if the change is working properly.
name: 1.19 Build (master)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # The corresponding tests are performed in the versions
    # marked as Long Term Support by Oracle and in its
    # latest version up to the moment.
    strategy:
      matrix:
        java: 17

    steps:
    # Checkout repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Setup a version of the Java JDK
    - name: Setup JAVA ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        architecture: x64

    # Start building Spigot
    - name: Build Spigot
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.19
    # An artifact is generated in a compressed file according to each JDK build version.
    - name: Upload Spigot
      uses: actions/upload-artifact@v3
      with:
        name: Spigot-JDK${{ matrix.java }}
        path: BuildFiles/1.19.jar
